/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohan
 */
public class CreateAccountJpanel extends javax.swing.JPanel {
    
    private JPanel container;
    private AccountDirectory directory;

    /**
     * Creates new form CreateAccountJpanel
     */
    public CreateAccountJpanel() {
        initComponents();
    }

    CreateAccountJpanel(JPanel container, AccountDirectory directory) {
        
        initComponents();
        this.container=container;
        this.directory=directory;
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCreateAccount = new javax.swing.JLabel();
        labelAccountNumber = new javax.swing.JLabel();
        labelRoutingNumber = new javax.swing.JLabel();
        labelBankName = new javax.swing.JLabel();
        labelBalance = new javax.swing.JLabel();
        textRoutingNumber = new javax.swing.JTextField();
        textAccountNumber = new javax.swing.JTextField();
        textBankName = new javax.swing.JTextField();
        textBalance = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        labelCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCreateAccount.setText("Create Account");

        labelAccountNumber.setText("Account Number:");

        labelRoutingNumber.setText("Routing Number:");

        labelBankName.setText("Bank Name:");

        labelBalance.setText("Balance:");

        buttonSubmit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonBack.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonBack.setText("<Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRoutingNumber)
                            .addComponent(labelBankName)
                            .addComponent(labelBalance)
                            .addComponent(labelAccountNumber))
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(buttonBack)
                        .addGap(403, 403, 403)
                        .addComponent(labelCreateAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(620, 620, 620)
                        .addComponent(buttonSubmit)))
                .addContainerGap(526, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(labelCreateAccount))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoutingNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAccountNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBankName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBalance))
                .addGap(53, 53, 53)
                .addComponent(buttonSubmit)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        
        container.remove(this);
        CardLayout layout=(CardLayout) container.getLayout();
        layout.previous(container);
        
        
        
        
        
        
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:

        String routingNumber= textRoutingNumber.getText();
        String accountNumber= textAccountNumber.getText();
        String bankName = textBankName.getText();
        int balance = Integer.parseInt(textBalance.getText());

        Account account=directory.addAccount();
        account.setAccountNumber(accountNumber);
        account.setBalance(balance);
        account.setBankName(bankName);
        account.setRoutingNumber(routingNumber);

        JOptionPane.showMessageDialog(null, "Account created succesfully!");

    }//GEN-LAST:event_buttonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel labelAccountNumber;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelBankName;
    private javax.swing.JLabel labelCreateAccount;
    private javax.swing.JLabel labelRoutingNumber;
    private javax.swing.JTextField textAccountNumber;
    private javax.swing.JTextField textBalance;
    private javax.swing.JTextField textBankName;
    private javax.swing.JTextField textRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
