/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.AccountDirectory;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author rohan
 */
public class MenuJPanel extends javax.swing.JPanel {
    private JPanel container;
    private AccountDirectory directory;

    /**
     * Creates new form MenuJPanel
     */
    
    MenuJPanel(JPanel Container, AccountDirectory directory) {
        initComponents();
        this.container=Container;
        this.directory= directory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCreateAccount = new javax.swing.JButton();
        buttonManageAccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        buttonCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCreateAccount.setText("Create Account");
        buttonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAccountActionPerformed(evt);
            }
        });

        buttonManageAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonManageAccount.setText("Manage Account");
        buttonManageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(buttonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(buttonManageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonManageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountActionPerformed
        // TODO add your handling code here:
        CreateAccountJpanel panel = new CreateAccountJpanel(container, directory);
        container.add("CreateAccountJPanel",panel);
        CardLayout layout= (CardLayout) container.getLayout();
        layout.next(container);
        
        
    }//GEN-LAST:event_buttonCreateAccountActionPerformed

    private void buttonManageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageAccountActionPerformed
        // TODO add your handling code here:
        ManageAccountJPanel panel= new ManageAccountJPanel(container,directory);
        container.add("ManageAccountJpanel",panel);
        CardLayout layout= (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_buttonManageAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateAccount;
    private javax.swing.JButton buttonManageAccount;
    // End of variables declaration//GEN-END:variables
}
