/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohan
 */
public class viewAccountJpanel extends javax.swing.JPanel {
    private JPanel container; 
    private Account account;
    private AccountDirectory directory;
    
    
    

    /**
     * Creates new form viewAccountJpanel
     */
    

    viewAccountJpanel(JPanel container, Account account, AccountDirectory directory) {
        initComponents();
        this.container= container;
        this.account= account;
        this.directory=directory;
        populateAccountDetails();
        buttonSave.setEnabled(false);
        buttonUpdate.setEnabled(true);
        
        textAccountNumber.setEditable(false);
        textBankName.setEditable(false);
        textRoutingNumber.setEditable(false);
        
        textAccountNumber.setEnabled(false);
        textBankName.setEnabled(false);
                
        textRoutingNumber.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelManageAccount = new javax.swing.JLabel();
        labelAccountNumber = new javax.swing.JLabel();
        labelRoutingNumber = new javax.swing.JLabel();
        labelBankName = new javax.swing.JLabel();
        textRoutingNumber = new javax.swing.JTextField();
        textAccountNumber = new javax.swing.JTextField();
        textBankName = new javax.swing.JTextField();
        buttonBack = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();

        labelManageAccount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelManageAccount.setText("Manage Account");

        labelAccountNumber.setText("Account Number:");

        labelRoutingNumber.setText("Routing Number:");

        labelBankName.setText("Bank Name:");

        buttonBack.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonBack.setText("<Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonSave.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.setEnabled(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRoutingNumber)
                            .addComponent(labelBankName)
                            .addComponent(labelAccountNumber))
                        .addGap(227, 227, 227)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(buttonBack)
                        .addGap(403, 403, 403)
                        .addComponent(labelManageAccount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 484, Short.MAX_VALUE)
                .addComponent(buttonUpdate)
                .addGap(130, 130, 130)
                .addComponent(buttonSave)
                .addGap(668, 668, 668))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(labelManageAccount))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoutingNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAccountNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBankName))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonUpdate))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1429, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:

        
        ManageAccountJPanel panel= new ManageAccountJPanel(container,directory);
        container.add("ManageAccountJpanel",panel);
        CardLayout layout= (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        account.setAccountNumber(textAccountNumber.getText());
        account.setBankName(textBankName.getText());
        account.setRoutingNumber(textRoutingNumber.getText());
        
        buttonSave.setEnabled(true);
        buttonUpdate.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Account updated succesfully!");
        
      
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        textAccountNumber.setEnabled(true);
        textBankName.setEnabled(true);
        textRoutingNumber.setEnabled(true);
        
        textAccountNumber.setEditable(true);
        textBankName.setEditable(true);
        textRoutingNumber.setEditable(true);
        
        buttonSave.setEnabled(true);
        buttonUpdate.setEnabled(false);
         
        
    }//GEN-LAST:event_buttonUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAccountNumber;
    private javax.swing.JLabel labelBankName;
    private javax.swing.JLabel labelManageAccount;
    private javax.swing.JLabel labelRoutingNumber;
    private javax.swing.JTextField textAccountNumber;
    private javax.swing.JTextField textBankName;
    private javax.swing.JTextField textRoutingNumber;
    // End of variables declaration//GEN-END:variables

    private void populateAccountDetails() {
        
        textAccountNumber.setText(account.getAccountNumber());
        textBankName.setText(account.getBankName());
        textRoutingNumber.setText(account.getRoutingNumber());
        
    }
}
